### ISSUE TITLE
ES6 computed properties cause "Duplicate data property in object literal not allowed in strict mode"

### ISSUE THREAD

**Issue by pecherf** [pigulla/grunt-jira-todo#3]
When using the ES6 Dynamic Object Key feature, you gain the following warning:

"Duplicate data property in object literal not allowed in strict mode Use --force to continue."

Example code:

```
var DYNAMIC_KEYS = {
        KEY1: 1,
        KEY2: 2
    },
    OBJECT_WITH_DYNAMIC_KEYS = {
        [KEY1]: 'a',
        [KEY2]: 'b'
    };
```

**Comment by pigulla** [comment]
This seems to be an issue with esprima-fb. Upstream has just recently added [support for computed object properties](http://blog.jquery.com/2015/03/10/esprima-2-1-released/) so as soon as that gets merged to esprima-fb we should be good. A workaround would be to remove the `"use strict"` statement.
